

set_property PACKAGE_PIN G15 [get_ports RES]
set_property IOSTANDARD LVCMOS33 [get_ports RES]
set_property PACKAGE_PIN T14 [get_ports AA]
set_property PACKAGE_PIN T15 [get_ports AB]
set_property PACKAGE_PIN P14 [get_ports AC]
set_property PACKAGE_PIN R14 [get_ports AD]
set_property PACKAGE_PIN V12 [get_ports AE]
set_property PACKAGE_PIN W16 [get_ports AF]
set_property PACKAGE_PIN J15 [get_ports AG]
set_property PACKAGE_PIN H15 [get_ports CAT]
set_property IOSTANDARD LVCMOS33 [get_ports AA]
set_property IOSTANDARD LVCMOS33 [get_ports AB]
set_property IOSTANDARD LVCMOS33 [get_ports AC]
set_property IOSTANDARD LVCMOS33 [get_ports AD]
set_property IOSTANDARD LVCMOS33 [get_ports AE]
set_property IOSTANDARD LVCMOS33 [get_ports AF]
set_property IOSTANDARD LVCMOS33 [get_ports AG]
set_property IOSTANDARD LVCMOS33 [get_ports CAT]
