#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat May 11 12:20:38 CEST 2024
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Licznik_99_x2_behav -key {Behavioral:sim_1:Functional:Licznik_99_x2} -tclbatch Licznik_99_x2.tcl -log simulate.log"
xsim Licznik_99_x2_behav -key {Behavioral:sim_1:Functional:Licznik_99_x2} -tclbatch Licznik_99_x2.tcl -log simulate.log

