version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "6969:6969"
    depends_on:
      - db

volumes:
  db_data:
